### ISSUE TITLE
Allows for saving of need with no requests

### ISSUE THREAD

**Issue by rushil-ambati** [Charity-Connect/reading-charity-connect#116]
When creating a need, and organisations match it, the system allows you to save the need after deselecting all organisations, creating a need in `client_needs` but with no respective requests in `need_requests`.

Do we assume that all needs will have need at minimum one corresponding request?

However when no organisations currently match that request we don't allow users to create that need, so for consistency we should disallow creation of needs that have no requests.

**Comment by mmillmor** [comment]
Can you describe the steps that someone can do today that you think are problematic?

**Comment by kiran-bahra** [comment]
So go to the client tab, then click on an individual client, then click to add a new request.
Fill in the information for the need so that it will match at least one offer. 
Then, you can deselect all offers (so that you aren't requesting any organisation) and then save the need, so the need is saved but it has no corresponding requests.

Therefore, this is a problem if we are making it so there cannot be any needs with no corresponding need request.
